server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql:3306/MicroServiceTaskDemo?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true